// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlbsIM90Dg5mJHM6yol81gYJ_W3T57Lw',
    appId: '1:328660672828:web:5d0c26ceeba437459a3e39',
    messagingSenderId: '328660672828',
    projectId: 'to-do-27a8a',
    authDomain: 'to-do-27a8a.firebaseapp.com',
    storageBucket: 'to-do-27a8a.appspot.com',
    measurementId: 'G-5SN17D0FHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rzMAS2mz4Wsfg2yl1XC7otmbXWXWXxo',
    appId: '1:328660672828:android:a18fdbe915b4c6769a3e39',
    messagingSenderId: '328660672828',
    projectId: 'to-do-27a8a',
    storageBucket: 'to-do-27a8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFlejBvPESaM2MwCVillaLjXcCgfyNa4',
    appId: '1:328660672828:ios:619701e36fc16b379a3e39',
    messagingSenderId: '328660672828',
    projectId: 'to-do-27a8a',
    storageBucket: 'to-do-27a8a.appspot.com',
    iosClientId: '328660672828-t12en3cqmlotur44jrk9thog132106h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfFlejBvPESaM2MwCVillaLjXcCgfyNa4',
    appId: '1:328660672828:ios:619701e36fc16b379a3e39',
    messagingSenderId: '328660672828',
    projectId: 'to-do-27a8a',
    storageBucket: 'to-do-27a8a.appspot.com',
    iosClientId: '328660672828-t12en3cqmlotur44jrk9thog132106h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoproject',
  );
}
